#!/bin/bash
set -e

. ./get-settings

case ",$NEWSADMINUSERS," in
*,"`whoami`",*) ;;
*)	echo >&2 "$0 must be run as one of $NEWSADMINUSERS, skipping"; exit 0;;
esac

exec <mailinglists_dir.part
while read alias group; do
	ctlinnd newgroup $group y
done

cd ..
cat live-*/mailinglists_dir.part >$MAILINGLISTSDIR.new
mv -f $MAILINGLISTSDIR.new $MAILINGLISTSDIR
