%OURUSER%+%ABBREV%+log+submissions:    %LOGGROUPPREFIX%.%ABBREV%.submissions
%OURUSER%+%ABBREV%+log+stump2webstump: %LOGGROUPPREFIX%.%ABBREV%.stump2webstump
%OURUSER%+%ABBREV%+log+webstump2stump: %LOGGROUPPREFIX%.%ABBREV%.webstump2stump
%OURUSER%+%ABBREV%+log+mailout:        %LOGGROUPPREFIX%.%ABBREV%.mailout
%OURUSER%+%ABBREV%+log+bounces:        %LOGGROUPPREFIX%.%ABBREV%.bounces
%OURUSER%+%ABBREV%+log+noack:          %LOGGROUPPREFIX%.%ABBREV%.noack
